#!/bin/sh
set -e

# Automatically added by dh_python3
if which py3compile >/dev/null 2>&1; then
	py3compile -p gobject-introspection:amd64 /usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner -V 3.10
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p gobject-introspection:amd64 /usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner -V 3.10 || true
fi

# End automatically added section
