#!/bin/sh
set -e
# Automatically added by dh_installalternatives/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
        update-alternatives --install /usr/bin/unrar unrar /usr/bin/unrar-nonfree 40 \
            --slave /usr/share/man/man1/unrar.1.gz unrar.1.gz /usr/share/man/man1/unrar-nonfree.1.gz
fi
# End automatically added section
