# Autogenerated wrapper script for Qt6ShaderTools_jll for i686-w64-mingw32-cxx03
export libqt6shadertools

using Qt6Base_jll
JLLWrappers.@generate_wrapper_header("Qt6ShaderTools")
JLLWrappers.@declare_library_product(libqt6shadertools, "Qt6ShaderTools.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll)
    JLLWrappers.@init_library_product(
        libqt6shadertools,
        "bin\\Qt6ShaderTools.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
