# Autogenerated wrapper script for Reactant_jll for x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt
export libReactantExtra

JLLWrappers.@generate_wrapper_header("Reactant")
JLLWrappers.@declare_library_product(libReactantExtra, "libReactantExtra.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libReactantExtra,
        "bin\\libReactantExtra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
