# Autogenerated wrapper script for Reactant_jll for x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt
export fatbinary, libReactantExtra, libcudnn, libcudnn_adv, libcudnn_cnn, libcudnn_engines_precompiled, libcudnn_engines_runtime_compiled, libcudnn_graph, libcudnn_heuristic, libcudnn_ops, libdevice, libnccl, libnvrtc, libnvrtc_builtins, libnvshmem_device, libnvshmem_host, nvshmem_bootstrap_uid, nvshmem_transport_ibrc, ptxas

JLLWrappers.@generate_wrapper_header("Reactant")
JLLWrappers.@declare_library_product(libReactantExtra, "libReactantExtra.so")
JLLWrappers.@declare_library_product(libcudnn, "libcudnn.so.9")
JLLWrappers.@declare_library_product(libcudnn_adv, "libcudnn_adv.so.9")
JLLWrappers.@declare_library_product(libcudnn_cnn, "libcudnn_cnn.so.9")
JLLWrappers.@declare_library_product(libcudnn_engines_precompiled, "libcudnn_engines_precompiled.so.9")
JLLWrappers.@declare_library_product(libcudnn_engines_runtime_compiled, "libcudnn_engines_runtime_compiled.so.9")
JLLWrappers.@declare_library_product(libcudnn_graph, "libcudnn_graph.so.9")
JLLWrappers.@declare_library_product(libcudnn_heuristic, "libcudnn_heuristic.so.9")
JLLWrappers.@declare_library_product(libcudnn_ops, "libcudnn_ops.so.9")
JLLWrappers.@declare_executable_product(fatbinary)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
JLLWrappers.@declare_library_product(libnvrtc, "libnvrtc.so.12")
JLLWrappers.@declare_library_product(libnvrtc_builtins, "libnvrtc-builtins.so.12.9")
JLLWrappers.@declare_file_product(libnvshmem_device)
JLLWrappers.@declare_library_product(libnvshmem_host, "libnvshmem_host.so.3")
JLLWrappers.@declare_library_product(nvshmem_bootstrap_uid, "nvshmem_bootstrap_uid.so.3")
JLLWrappers.@declare_library_product(nvshmem_transport_ibrc, "nvshmem_transport_ibrc.so.3")
JLLWrappers.@declare_executable_product(ptxas)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libReactantExtra,
        "lib/libReactantExtra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcudnn,
        "lib/libcudnn.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_adv,
        "lib/libcudnn_adv.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_cnn,
        "lib/libcudnn_cnn.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_engines_precompiled,
        "lib/libcudnn_engines_precompiled.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_engines_runtime_compiled,
        "lib/libcudnn_engines_runtime_compiled.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_graph,
        "lib/libcudnn_graph.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_heuristic,
        "lib/libcudnn_heuristic.so.9",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libcudnn_ops,
        "lib/libcudnn_ops.so.9",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        fatbinary,
        "lib/cuda/bin/fatbinary",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "lib/cuda/nvvm/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so.2",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvrtc,
        "lib/libnvrtc.so.12",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libnvrtc_builtins,
        "lib/libnvrtc-builtins.so.12.9",
        nothing,
    )

    JLLWrappers.@init_file_product(
        libnvshmem_device,
        "lib/libnvshmem_device.bc",
    )

    JLLWrappers.@init_library_product(
        libnvshmem_host,
        "lib/libnvshmem_host.so.3",
        nothing,
    )

    JLLWrappers.@init_library_product(
        nvshmem_bootstrap_uid,
        "lib/nvshmem_bootstrap_uid.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        nvshmem_transport_ibrc,
        "lib/nvshmem_transport_ibrc.so.3",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "lib/cuda/bin/ptxas",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
