# Autogenerated wrapper script for Reactant_jll for x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt
export libReactantExtra, libamdhip64, libhipfft, libhiprtc, libhiprtc_builtins, libhipsolver, libhipsolver_fortran, libhsa_runtime64, librccl, librocm_core, librocm_smi64, librocprofiler_register, librocsolver

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Reactant")
JLLWrappers.@declare_library_product(libReactantExtra, "libReactantExtra.so")
JLLWrappers.@declare_library_product(libamdhip64, "libamdhip64.so.7")
JLLWrappers.@declare_library_product(libhipfft, "libhipfft.so.0")
JLLWrappers.@declare_library_product(libhiprtc, "libhiprtc.so.7")
JLLWrappers.@declare_library_product(libhiprtc_builtins, "libhiprtc-builtins.so.7")
JLLWrappers.@declare_library_product(libhipsolver, "libhipsolver.so.1")
JLLWrappers.@declare_library_product(libhipsolver_fortran, "libhipsolver_fortran.so.1")
JLLWrappers.@declare_library_product(libhsa_runtime64, "libhsa-runtime64.so.1")
JLLWrappers.@declare_library_product(librccl, "librccl.so.1")
JLLWrappers.@declare_library_product(librocm_core, "librocm-core.so.1")
JLLWrappers.@declare_library_product(librocm_smi64, "librocm_smi64.so.1")
JLLWrappers.@declare_library_product(librocprofiler_register, "librocprofiler-register.so.0")
JLLWrappers.@declare_library_product(librocsolver, "librocsolver.so.0")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libReactantExtra,
        "lib/libReactantExtra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libamdhip64,
        "lib/libamdhip64.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhipfft,
        "lib/libhipfft.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhiprtc,
        "lib/libhiprtc.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhiprtc_builtins,
        "lib/libhiprtc-builtins.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhipsolver,
        "lib/libhipsolver.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhipsolver_fortran,
        "lib/libhipsolver_fortran.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libhsa_runtime64,
        "lib/libhsa-runtime64.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        librccl,
        "lib/librccl.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        librocm_core,
        "lib/librocm-core.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        librocm_smi64,
        "lib/librocm_smi64.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        librocprofiler_register,
        "lib/librocprofiler-register.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        librocsolver,
        "lib/librocsolver.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
