# Autogenerated wrapper script for Qt6Declarative_jll for aarch64-linux-gnu-cxx11
export libqt6labsanimation, libqt6labsfolderlistmodel, libqt6labsqmlmodels, libqt6labssettings, libqt6labssharedimage, libqt6labswavefrontmesh, libqt6qml, libqt6qmlcompiler, libqt6qmlcore, libqt6qmllocalstorage, libqt6qmlmodels, libqt6qmlnetwork, libqt6qmlworkerscript, libqt6qmlxmllistmodel, libqt6quick, libqt6quickcontrols2, libqt6quickcontrols2basic, libqt6quickcontrols2basicstyleimpl, libqt6quickcontrols2fusion, libqt6quickcontrols2fusionstyleimpl, libqt6quickcontrols2imagine, libqt6quickcontrols2imaginestyleimpl, libqt6quickcontrols2impl, libqt6quickcontrols2material, libqt6quickcontrols2materialstyleimpl, libqt6quickcontrols2universal, libqt6quickcontrols2universalstyleimpl, libqt6quickdialogs2, libqt6quickdialogs2quickimpl, libqt6quickdialogs2utils, libqt6quickeffects, libqt6quicklayouts, libqt6quickparticles, libqt6quickshapes, libqt6quicktemplates2, libqt6quicktest, libqt6quickwidgets

using Qt6Base_jll
using Qt6ShaderTools_jll
JLLWrappers.@generate_wrapper_header("Qt6Declarative")
JLLWrappers.@declare_library_product(libqt6labsanimation, "libQt6LabsAnimation.so.6")
JLLWrappers.@declare_library_product(libqt6labsfolderlistmodel, "libQt6LabsFolderListModel.so.6")
JLLWrappers.@declare_library_product(libqt6labsqmlmodels, "libQt6LabsQmlModels.so.6")
JLLWrappers.@declare_library_product(libqt6labssettings, "libQt6LabsSettings.so.6")
JLLWrappers.@declare_library_product(libqt6labssharedimage, "libQt6LabsSharedImage.so.6")
JLLWrappers.@declare_library_product(libqt6labswavefrontmesh, "libQt6LabsWavefrontMesh.so.6")
JLLWrappers.@declare_library_product(libqt6qml, "libQt6Qml.so.6")
JLLWrappers.@declare_library_product(libqt6qmlcompiler, "libQt6QmlCompiler.so.6")
JLLWrappers.@declare_library_product(libqt6qmlcore, "libQt6QmlCore.so.6")
JLLWrappers.@declare_library_product(libqt6qmllocalstorage, "libQt6QmlLocalStorage.so.6")
JLLWrappers.@declare_library_product(libqt6qmlmodels, "libQt6QmlModels.so.6")
JLLWrappers.@declare_library_product(libqt6qmlnetwork, "libQt6QmlNetwork.so.6")
JLLWrappers.@declare_library_product(libqt6qmlworkerscript, "libQt6QmlWorkerScript.so.6")
JLLWrappers.@declare_library_product(libqt6qmlxmllistmodel, "libQt6QmlXmlListModel.so.6")
JLLWrappers.@declare_library_product(libqt6quick, "libQt6Quick.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2, "libQt6QuickControls2.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basic, "libQt6QuickControls2Basic.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basicstyleimpl, "libQt6QuickControls2BasicStyleImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusion, "libQt6QuickControls2Fusion.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusionstyleimpl, "libQt6QuickControls2FusionStyleImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imagine, "libQt6QuickControls2Imagine.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imaginestyleimpl, "libQt6QuickControls2ImagineStyleImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2impl, "libQt6QuickControls2Impl.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2material, "libQt6QuickControls2Material.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2materialstyleimpl, "libQt6QuickControls2MaterialStyleImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universal, "libQt6QuickControls2Universal.so.6")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universalstyleimpl, "libQt6QuickControls2UniversalStyleImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickdialogs2, "libQt6QuickDialogs2.so.6")
JLLWrappers.@declare_library_product(libqt6quickdialogs2quickimpl, "libQt6QuickDialogs2QuickImpl.so.6")
JLLWrappers.@declare_library_product(libqt6quickdialogs2utils, "libQt6QuickDialogs2Utils.so.6")
JLLWrappers.@declare_library_product(libqt6quickeffects, "libQt6QuickEffects.so.6")
JLLWrappers.@declare_library_product(libqt6quicklayouts, "libQt6QuickLayouts.so.6")
JLLWrappers.@declare_library_product(libqt6quickparticles, "libQt6QuickParticles.so.6")
JLLWrappers.@declare_library_product(libqt6quickshapes, "libQt6QuickShapes.so.6")
JLLWrappers.@declare_library_product(libqt6quicktemplates2, "libQt6QuickTemplates2.so.6")
JLLWrappers.@declare_library_product(libqt6quicktest, "libQt6QuickTest.so.6")
JLLWrappers.@declare_library_product(libqt6quickwidgets, "libQt6QuickWidgets.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6ShaderTools_jll)
    JLLWrappers.@init_library_product(
        libqt6labsanimation,
        "lib/libQt6LabsAnimation.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsfolderlistmodel,
        "lib/libQt6LabsFolderListModel.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsqmlmodels,
        "lib/libQt6LabsQmlModels.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssettings,
        "lib/libQt6LabsSettings.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssharedimage,
        "lib/libQt6LabsSharedImage.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labswavefrontmesh,
        "lib/libQt6LabsWavefrontMesh.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qml,
        "lib/libQt6Qml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcompiler,
        "lib/libQt6QmlCompiler.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcore,
        "lib/libQt6QmlCore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmllocalstorage,
        "lib/libQt6QmlLocalStorage.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlmodels,
        "lib/libQt6QmlModels.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlnetwork,
        "lib/libQt6QmlNetwork.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlworkerscript,
        "lib/libQt6QmlWorkerScript.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlxmllistmodel,
        "lib/libQt6QmlXmlListModel.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick,
        "lib/libQt6Quick.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2,
        "lib/libQt6QuickControls2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basic,
        "lib/libQt6QuickControls2Basic.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basicstyleimpl,
        "lib/libQt6QuickControls2BasicStyleImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusion,
        "lib/libQt6QuickControls2Fusion.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusionstyleimpl,
        "lib/libQt6QuickControls2FusionStyleImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imagine,
        "lib/libQt6QuickControls2Imagine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imaginestyleimpl,
        "lib/libQt6QuickControls2ImagineStyleImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2impl,
        "lib/libQt6QuickControls2Impl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2material,
        "lib/libQt6QuickControls2Material.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2materialstyleimpl,
        "lib/libQt6QuickControls2MaterialStyleImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universal,
        "lib/libQt6QuickControls2Universal.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universalstyleimpl,
        "lib/libQt6QuickControls2UniversalStyleImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2,
        "lib/libQt6QuickDialogs2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2quickimpl,
        "lib/libQt6QuickDialogs2QuickImpl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2utils,
        "lib/libQt6QuickDialogs2Utils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickeffects,
        "lib/libQt6QuickEffects.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicklayouts,
        "lib/libQt6QuickLayouts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickparticles,
        "lib/libQt6QuickParticles.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickshapes,
        "lib/libQt6QuickShapes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktemplates2,
        "lib/libQt6QuickTemplates2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktest,
        "lib/libQt6QuickTest.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickwidgets,
        "lib/libQt6QuickWidgets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
