# Autogenerated wrapper script for Qt6Declarative_jll for i686-w64-mingw32-cxx03
export libqt6labsanimation, libqt6labsfolderlistmodel, libqt6labsqmlmodels, libqt6labssettings, libqt6labssharedimage, libqt6labswavefrontmesh, libqt6qml, libqt6qmlcompiler, libqt6qmlcore, libqt6qmllocalstorage, libqt6qmlmodels, libqt6qmlnetwork, libqt6qmlworkerscript, libqt6qmlxmllistmodel, libqt6quick, libqt6quickcontrols2, libqt6quickcontrols2basic, libqt6quickcontrols2basicstyleimpl, libqt6quickcontrols2fusion, libqt6quickcontrols2fusionstyleimpl, libqt6quickcontrols2imagine, libqt6quickcontrols2imaginestyleimpl, libqt6quickcontrols2impl, libqt6quickcontrols2material, libqt6quickcontrols2materialstyleimpl, libqt6quickcontrols2universal, libqt6quickcontrols2universalstyleimpl, libqt6quickcontrols2windowsstyleimpl, libqt6quickdialogs2, libqt6quickdialogs2quickimpl, libqt6quickdialogs2utils, libqt6quickeffects, libqt6quicklayouts, libqt6quickparticles, libqt6quickshapes, libqt6quicktemplates2, libqt6quicktest, libqt6quickwidgets

using Qt6Base_jll
using Qt6ShaderTools_jll
JLLWrappers.@generate_wrapper_header("Qt6Declarative")
JLLWrappers.@declare_library_product(libqt6labsanimation, "Qt6LabsAnimation.dll")
JLLWrappers.@declare_library_product(libqt6labsfolderlistmodel, "Qt6LabsFolderListModel.dll")
JLLWrappers.@declare_library_product(libqt6labsqmlmodels, "Qt6LabsQmlModels.dll")
JLLWrappers.@declare_library_product(libqt6labssettings, "Qt6LabsSettings.dll")
JLLWrappers.@declare_library_product(libqt6labssharedimage, "Qt6LabsSharedImage.dll")
JLLWrappers.@declare_library_product(libqt6labswavefrontmesh, "Qt6LabsWavefrontMesh.dll")
JLLWrappers.@declare_library_product(libqt6qml, "Qt6Qml.dll")
JLLWrappers.@declare_library_product(libqt6qmlcompiler, "Qt6QmlCompiler.dll")
JLLWrappers.@declare_library_product(libqt6qmlcore, "Qt6QmlCore.dll")
JLLWrappers.@declare_library_product(libqt6qmllocalstorage, "Qt6QmlLocalStorage.dll")
JLLWrappers.@declare_library_product(libqt6qmlmodels, "Qt6QmlModels.dll")
JLLWrappers.@declare_library_product(libqt6qmlnetwork, "Qt6QmlNetwork.dll")
JLLWrappers.@declare_library_product(libqt6qmlworkerscript, "Qt6QmlWorkerScript.dll")
JLLWrappers.@declare_library_product(libqt6qmlxmllistmodel, "Qt6QmlXmlListModel.dll")
JLLWrappers.@declare_library_product(libqt6quick, "Qt6Quick.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2, "Qt6QuickControls2.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basic, "Qt6QuickControls2Basic.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basicstyleimpl, "Qt6QuickControls2BasicStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusion, "Qt6QuickControls2Fusion.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusionstyleimpl, "Qt6QuickControls2FusionStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imagine, "Qt6QuickControls2Imagine.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imaginestyleimpl, "Qt6QuickControls2ImagineStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2impl, "Qt6QuickControls2Impl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2material, "Qt6QuickControls2Material.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2materialstyleimpl, "Qt6QuickControls2MaterialStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universal, "Qt6QuickControls2Universal.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universalstyleimpl, "Qt6QuickControls2UniversalStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickcontrols2windowsstyleimpl, "Qt6QuickControls2WindowsStyleImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickdialogs2, "Qt6QuickDialogs2.dll")
JLLWrappers.@declare_library_product(libqt6quickdialogs2quickimpl, "Qt6QuickDialogs2QuickImpl.dll")
JLLWrappers.@declare_library_product(libqt6quickdialogs2utils, "Qt6QuickDialogs2Utils.dll")
JLLWrappers.@declare_library_product(libqt6quickeffects, "Qt6QuickEffects.dll")
JLLWrappers.@declare_library_product(libqt6quicklayouts, "Qt6QuickLayouts.dll")
JLLWrappers.@declare_library_product(libqt6quickparticles, "Qt6QuickParticles.dll")
JLLWrappers.@declare_library_product(libqt6quickshapes, "Qt6QuickShapes.dll")
JLLWrappers.@declare_library_product(libqt6quicktemplates2, "Qt6QuickTemplates2.dll")
JLLWrappers.@declare_library_product(libqt6quicktest, "Qt6QuickTest.dll")
JLLWrappers.@declare_library_product(libqt6quickwidgets, "Qt6QuickWidgets.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6ShaderTools_jll)
    JLLWrappers.@init_library_product(
        libqt6labsanimation,
        "bin\\Qt6LabsAnimation.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsfolderlistmodel,
        "bin\\Qt6LabsFolderListModel.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsqmlmodels,
        "bin\\Qt6LabsQmlModels.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssettings,
        "bin\\Qt6LabsSettings.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssharedimage,
        "bin\\Qt6LabsSharedImage.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labswavefrontmesh,
        "bin\\Qt6LabsWavefrontMesh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qml,
        "bin\\Qt6Qml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcompiler,
        "bin\\Qt6QmlCompiler.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcore,
        "bin\\Qt6QmlCore.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmllocalstorage,
        "bin\\Qt6QmlLocalStorage.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlmodels,
        "bin\\Qt6QmlModels.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlnetwork,
        "bin\\Qt6QmlNetwork.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlworkerscript,
        "bin\\Qt6QmlWorkerScript.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlxmllistmodel,
        "bin\\Qt6QmlXmlListModel.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick,
        "bin\\Qt6Quick.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2,
        "bin\\Qt6QuickControls2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basic,
        "bin\\Qt6QuickControls2Basic.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basicstyleimpl,
        "bin\\Qt6QuickControls2BasicStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusion,
        "bin\\Qt6QuickControls2Fusion.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusionstyleimpl,
        "bin\\Qt6QuickControls2FusionStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imagine,
        "bin\\Qt6QuickControls2Imagine.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imaginestyleimpl,
        "bin\\Qt6QuickControls2ImagineStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2impl,
        "bin\\Qt6QuickControls2Impl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2material,
        "bin\\Qt6QuickControls2Material.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2materialstyleimpl,
        "bin\\Qt6QuickControls2MaterialStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universal,
        "bin\\Qt6QuickControls2Universal.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universalstyleimpl,
        "bin\\Qt6QuickControls2UniversalStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2windowsstyleimpl,
        "bin\\Qt6QuickControls2WindowsStyleImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2,
        "bin\\Qt6QuickDialogs2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2quickimpl,
        "bin\\Qt6QuickDialogs2QuickImpl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2utils,
        "bin\\Qt6QuickDialogs2Utils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickeffects,
        "bin\\Qt6QuickEffects.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicklayouts,
        "bin\\Qt6QuickLayouts.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickparticles,
        "bin\\Qt6QuickParticles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickshapes,
        "bin\\Qt6QuickShapes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktemplates2,
        "bin\\Qt6QuickTemplates2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktest,
        "bin\\Qt6QuickTest.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickwidgets,
        "bin\\Qt6QuickWidgets.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
