# Autogenerated wrapper script for Qt6Declarative_jll for x86_64-apple-darwin
export libqt6labsanimation, libqt6labsfolderlistmodel, libqt6labsqmlmodels, libqt6labssettings, libqt6labssharedimage, libqt6labswavefrontmesh, libqt6qml, libqt6qmlcompiler, libqt6qmlcore, libqt6qmllocalstorage, libqt6qmlmodels, libqt6qmlnetwork, libqt6qmlworkerscript, libqt6qmlxmllistmodel, libqt6quick, libqt6quickcontrols2, libqt6quickcontrols2basic, libqt6quickcontrols2basicstyleimpl, libqt6quickcontrols2fusion, libqt6quickcontrols2fusionstyleimpl, libqt6quickcontrols2imagine, libqt6quickcontrols2imaginestyleimpl, libqt6quickcontrols2impl, libqt6quickcontrols2material, libqt6quickcontrols2materialstyleimpl, libqt6quickcontrols2universal, libqt6quickcontrols2universalstyleimpl, libqt6quickdialogs2, libqt6quickdialogs2quickimpl, libqt6quickdialogs2utils, libqt6quickeffects, libqt6quicklayouts, libqt6quickparticles, libqt6quickshapes, libqt6quicktemplates2, libqt6quicktest, libqt6quickwidgets

using Qt6Base_jll
using Qt6ShaderTools_jll
JLLWrappers.@generate_wrapper_header("Qt6Declarative")
JLLWrappers.@declare_library_product(libqt6labsanimation, "@rpath/QtLabsAnimation")
JLLWrappers.@declare_library_product(libqt6labsfolderlistmodel, "@rpath/QtLabsFolderListModel")
JLLWrappers.@declare_library_product(libqt6labsqmlmodels, "@rpath/QtLabsQmlModels")
JLLWrappers.@declare_library_product(libqt6labssettings, "@rpath/QtLabsSettings")
JLLWrappers.@declare_library_product(libqt6labssharedimage, "@rpath/QtLabsSharedImage")
JLLWrappers.@declare_library_product(libqt6labswavefrontmesh, "@rpath/QtLabsWavefrontMesh")
JLLWrappers.@declare_library_product(libqt6qml, "@rpath/QtQml")
JLLWrappers.@declare_library_product(libqt6qmlcompiler, "@rpath/QtQmlCompiler")
JLLWrappers.@declare_library_product(libqt6qmlcore, "@rpath/QtQmlCore")
JLLWrappers.@declare_library_product(libqt6qmllocalstorage, "@rpath/QtQmlLocalStorage")
JLLWrappers.@declare_library_product(libqt6qmlmodels, "@rpath/QtQmlModels")
JLLWrappers.@declare_library_product(libqt6qmlnetwork, "@rpath/QtQmlNetwork")
JLLWrappers.@declare_library_product(libqt6qmlworkerscript, "@rpath/QtQmlWorkerScript")
JLLWrappers.@declare_library_product(libqt6qmlxmllistmodel, "@rpath/QtQmlXmlListModel")
JLLWrappers.@declare_library_product(libqt6quick, "@rpath/QtQuick")
JLLWrappers.@declare_library_product(libqt6quickcontrols2, "@rpath/QtQuickControls2")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basic, "@rpath/QtQuickControls2Basic")
JLLWrappers.@declare_library_product(libqt6quickcontrols2basicstyleimpl, "@rpath/QtQuickControls2BasicStyleImpl")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusion, "@rpath/QtQuickControls2Fusion")
JLLWrappers.@declare_library_product(libqt6quickcontrols2fusionstyleimpl, "@rpath/QtQuickControls2FusionStyleImpl")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imagine, "@rpath/QtQuickControls2Imagine")
JLLWrappers.@declare_library_product(libqt6quickcontrols2imaginestyleimpl, "@rpath/QtQuickControls2ImagineStyleImpl")
JLLWrappers.@declare_library_product(libqt6quickcontrols2impl, "@rpath/QtQuickControls2Impl")
JLLWrappers.@declare_library_product(libqt6quickcontrols2material, "@rpath/QtQuickControls2Material")
JLLWrappers.@declare_library_product(libqt6quickcontrols2materialstyleimpl, "@rpath/QtQuickControls2MaterialStyleImpl")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universal, "@rpath/QtQuickControls2Universal")
JLLWrappers.@declare_library_product(libqt6quickcontrols2universalstyleimpl, "@rpath/QtQuickControls2UniversalStyleImpl")
JLLWrappers.@declare_library_product(libqt6quickdialogs2, "@rpath/QtQuickDialogs2")
JLLWrappers.@declare_library_product(libqt6quickdialogs2quickimpl, "@rpath/QtQuickDialogs2QuickImpl")
JLLWrappers.@declare_library_product(libqt6quickdialogs2utils, "@rpath/QtQuickDialogs2Utils")
JLLWrappers.@declare_library_product(libqt6quickeffects, "@rpath/QtQuickEffects")
JLLWrappers.@declare_library_product(libqt6quicklayouts, "@rpath/QtQuickLayouts")
JLLWrappers.@declare_library_product(libqt6quickparticles, "@rpath/QtQuickParticles")
JLLWrappers.@declare_library_product(libqt6quickshapes, "@rpath/QtQuickShapes")
JLLWrappers.@declare_library_product(libqt6quicktemplates2, "@rpath/QtQuickTemplates2")
JLLWrappers.@declare_library_product(libqt6quicktest, "@rpath/QtQuickTest")
JLLWrappers.@declare_library_product(libqt6quickwidgets, "@rpath/QtQuickWidgets")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6ShaderTools_jll)
    JLLWrappers.@init_library_product(
        libqt6labsanimation,
        "lib/QtLabsAnimation.framework/Versions/A/QtLabsAnimation",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsfolderlistmodel,
        "lib/QtLabsFolderListModel.framework/Versions/A/QtLabsFolderListModel",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labsqmlmodels,
        "lib/QtLabsQmlModels.framework/Versions/A/QtLabsQmlModels",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssettings,
        "lib/QtLabsSettings.framework/Versions/A/QtLabsSettings",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labssharedimage,
        "lib/QtLabsSharedImage.framework/Versions/A/QtLabsSharedImage",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6labswavefrontmesh,
        "lib/QtLabsWavefrontMesh.framework/Versions/A/QtLabsWavefrontMesh",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qml,
        "lib/QtQml.framework/Versions/A/QtQml",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcompiler,
        "lib/QtQmlCompiler.framework/Versions/A/QtQmlCompiler",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlcore,
        "lib/QtQmlCore.framework/Versions/A/QtQmlCore",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmllocalstorage,
        "lib/QtQmlLocalStorage.framework/Versions/A/QtQmlLocalStorage",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlmodels,
        "lib/QtQmlModels.framework/Versions/A/QtQmlModels",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlnetwork,
        "lib/QtQmlNetwork.framework/Versions/A/QtQmlNetwork",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlworkerscript,
        "lib/QtQmlWorkerScript.framework/Versions/A/QtQmlWorkerScript",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6qmlxmllistmodel,
        "lib/QtQmlXmlListModel.framework/Versions/A/QtQmlXmlListModel",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quick,
        "lib/QtQuick.framework/Versions/A/QtQuick",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2,
        "lib/QtQuickControls2.framework/Versions/A/QtQuickControls2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basic,
        "lib/QtQuickControls2Basic.framework/Versions/A/QtQuickControls2Basic",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2basicstyleimpl,
        "lib/QtQuickControls2BasicStyleImpl.framework/Versions/A/QtQuickControls2BasicStyleImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusion,
        "lib/QtQuickControls2Fusion.framework/Versions/A/QtQuickControls2Fusion",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2fusionstyleimpl,
        "lib/QtQuickControls2FusionStyleImpl.framework/Versions/A/QtQuickControls2FusionStyleImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imagine,
        "lib/QtQuickControls2Imagine.framework/Versions/A/QtQuickControls2Imagine",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2imaginestyleimpl,
        "lib/QtQuickControls2ImagineStyleImpl.framework/Versions/A/QtQuickControls2ImagineStyleImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2impl,
        "lib/QtQuickControls2Impl.framework/Versions/A/QtQuickControls2Impl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2material,
        "lib/QtQuickControls2Material.framework/Versions/A/QtQuickControls2Material",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2materialstyleimpl,
        "lib/QtQuickControls2MaterialStyleImpl.framework/Versions/A/QtQuickControls2MaterialStyleImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universal,
        "lib/QtQuickControls2Universal.framework/Versions/A/QtQuickControls2Universal",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickcontrols2universalstyleimpl,
        "lib/QtQuickControls2UniversalStyleImpl.framework/Versions/A/QtQuickControls2UniversalStyleImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2,
        "lib/QtQuickDialogs2.framework/Versions/A/QtQuickDialogs2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2quickimpl,
        "lib/QtQuickDialogs2QuickImpl.framework/Versions/A/QtQuickDialogs2QuickImpl",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickdialogs2utils,
        "lib/QtQuickDialogs2Utils.framework/Versions/A/QtQuickDialogs2Utils",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickeffects,
        "lib/QtQuickEffects.framework/Versions/A/QtQuickEffects",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicklayouts,
        "lib/QtQuickLayouts.framework/Versions/A/QtQuickLayouts",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickparticles,
        "lib/QtQuickParticles.framework/Versions/A/QtQuickParticles",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickshapes,
        "lib/QtQuickShapes.framework/Versions/A/QtQuickShapes",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktemplates2,
        "lib/QtQuickTemplates2.framework/Versions/A/QtQuickTemplates2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quicktest,
        "lib/QtQuickTest.framework/Versions/A/QtQuickTest",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6quickwidgets,
        "lib/QtQuickWidgets.framework/Versions/A/QtQuickWidgets",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
